export const outbreakData = [
  {
    name: "Influenza A (H3N2)",
    status: "Increasing Rapidly",
    severity_level: "Medium",
    location: "Your City",
    description:
      "Reported cases have doubled in the past week, with clusters around downtown clinics and schools.",
  },
  {
    name: "Norovirus",
    status: "High Alert",
    severity_level: "High",
    location: "Nearby Region",
    description:
      "Multiple outbreaks linked to local restaurants; symptoms include vomiting and diarrhea.",
  },
  {
    name: "RSV",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Your City",
    description:
      "Pediatric cases are rising; hospitals recommend masks for high-risk groups.",
  },
  {
    name: "COVID-19 (Omicron Variant)",
    status: "Increasing Rapidly",
    severity_level: "High",
    location: "Regional",
    description:
      "New variant cases are spreading quickly with clusters in workplaces and schools.",
  },
  {
    name: "Measles",
    status: "Outbreak",
    severity_level: "High",
    location: "Your City",
    description:
      "Several unvaccinated children have tested positive; health officials urge vaccination.",
  },
  {
    name: "Chickenpox",
    status: "Stable",
    severity_level: "Low",
    location: "Nearby Schools",
    description:
      "Isolated cases reported in primary schools; monitoring ongoing.",
  },
  {
    name: "Mumps",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Community Centers",
    description: "Clusters reported among adolescents and young adults.",
  },
  {
    name: "Dengue Fever",
    status: "Seasonal Rise",
    severity_level: "High",
    location: "Regional",
    description: "Mosquito-borne cases increasing due to monsoon season.",
  },
  {
    name: "Zika Virus",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Nearby Region",
    description: "Health officials warn pregnant women to take precautions.",
  },
  {
    name: "Chikungunya",
    status: "Increasing Slowly",
    severity_level: "Medium",
    location: "Local District",
    description: "Cases of fever and joint pain rising in suburban areas.",
  },
  {
    name: "Hepatitis A",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Nearby Restaurants",
    description: "Linked to contaminated food in local eateries.",
  },
  {
    name: "Hepatitis B",
    status: "Stable",
    severity_level: "Medium",
    location: "Regional",
    description:
      "Routine screenings detect new cases; vaccination recommended.",
  },
  {
    name: "Hepatitis C",
    status: "Increasing Slowly",
    severity_level: "High",
    location: "Regional",
    description:
      "Detected mostly in high-risk groups through blood screenings.",
  },
  {
    name: "Tuberculosis (TB)",
    status: "Ongoing",
    severity_level: "High",
    location: "Your City",
    description: "Hospitals report rise in drug-resistant TB strains.",
  },
  {
    name: "Whooping Cough (Pertussis)",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Nearby Schools",
    description: "Clusters of coughing illness in unvaccinated children.",
  },
  {
    name: "Polio",
    status: "Isolated Case",
    severity_level: "High",
    location: "Nearby Region",
    description: "Rare polio case detected; vaccination drive underway.",
  },
  {
    name: "Tetanus",
    status: "Stable",
    severity_level: "Medium",
    location: "Hospitals",
    description: "Cases reported mostly from injury-related exposures.",
  },
  {
    name: "Malaria",
    status: "Seasonal Rise",
    severity_level: "High",
    location: "Regional",
    description: "Mosquito-borne illness spiking after heavy rainfall.",
  },
  {
    name: "Yellow Fever",
    status: "Travel Advisory",
    severity_level: "High",
    location: "International",
    description: "Travel-related risk reported; vaccination recommended.",
  },
  {
    name: "Ebola",
    status: "Contained",
    severity_level: "High",
    location: "International",
    description: "Outbreak in African region under control, no local spread.",
  },
  {
    name: "Marburg Virus",
    status: "Isolated Outbreak",
    severity_level: "High",
    location: "International",
    description:
      "Rare viral outbreak detected; international monitoring ongoing.",
  },
  {
    name: "Hantavirus",
    status: "Isolated Case",
    severity_level: "Medium",
    location: "Nearby Region",
    description: "Single case linked to rodent exposure in rural areas.",
  },
  {
    name: "Lyme Disease",
    status: "Seasonal Increase",
    severity_level: "Medium",
    location: "Regional",
    description: "Cases linked to tick bites rising during summer months.",
  },
  {
    name: "Rabies",
    status: "Ongoing",
    severity_level: "High",
    location: "Nearby Villages",
    description: "Cases reported in stray animals; vaccination drives ongoing.",
  },
  {
    name: "Avian Influenza (H5N1)",
    status: "Outbreak",
    severity_level: "High",
    location: "Regional Poultry Farms",
    description: "Linked to poultry exposure; monitoring for human cases.",
  },
  {
    name: "Swine Flu (H1N1)",
    status: "Increasing Rapidly",
    severity_level: "Medium",
    location: "Your City",
    description: "Respiratory illness clusters reported in schools.",
  },
  {
    name: "Common Cold",
    status: "Stable",
    severity_level: "Low",
    location: "Community",
    description: "Expected seasonal cases reported; no unusual patterns.",
  },
  {
    name: "Seasonal Flu",
    status: "Seasonal Rise",
    severity_level: "Medium",
    location: "Regional",
    description:
      "Health officials encourage flu vaccination for vulnerable groups.",
  },
  {
    name: "Hand, Foot, and Mouth Disease (HFMD)",
    status: "Outbreak",
    severity_level: "Low",
    location: "Nearby Schools",
    description: "Clusters in preschool children reported.",
  },
  {
    name: "Scarlet Fever",
    status: "Increasing Slowly",
    severity_level: "Medium",
    location: "Your City",
    description: "Cases linked to strep infections in children.",
  },
  {
    name: "Meningitis (Bacterial)",
    status: "High Alert",
    severity_level: "High",
    location: "Regional Hospitals",
    description:
      "Severe cases require hospitalization; vaccination recommended.",
  },
  {
    name: "Meningitis (Viral)",
    status: "Stable",
    severity_level: "Medium",
    location: "Nearby Region",
    description: "Mild cases being monitored; no severe outbreaks reported.",
  },
  {
    name: "Cholera",
    status: "Outbreak",
    severity_level: "High",
    location: "Nearby Villages",
    description: "Contaminated water linked to multiple diarrheal cases.",
  },
  {
    name: "Typhoid Fever",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Nearby Restaurants",
    description: "Foodborne illness reported in multiple households.",
  },
  {
    name: "Plague",
    status: "Isolated Case",
    severity_level: "High",
    location: "International",
    description: "Rare bubonic plague case detected; no spread reported.",
  },
  {
    name: "Leptospirosis",
    status: "Seasonal Rise",
    severity_level: "Medium",
    location: "Flood-Prone Areas",
    description: "Waterborne disease increasing after heavy rainfall.",
  },
  {
    name: "Anthrax",
    status: "Outbreak",
    severity_level: "High",
    location: "Nearby Farms",
    description: "Linked to livestock exposure; vaccination campaign ongoing.",
  },
  {
    name: "Syphilis",
    status: "Increasing Slowly",
    severity_level: "Medium",
    location: "Regional",
    description: "Rise in sexually transmitted infections detected.",
  },
  {
    name: "Gonorrhea",
    status: "Stable",
    severity_level: "Medium",
    location: "Regional",
    description: "Drug-resistant strains being monitored closely.",
  },
  {
    name: "HIV/AIDS",
    status: "Ongoing",
    severity_level: "High",
    location: "Regional",
    description: "Ongoing awareness and testing campaigns in communities.",
  },
  {
    name: "Mpox (Monkeypox)",
    status: "Outbreak",
    severity_level: "Medium",
    location: "Nearby Region",
    description: "Clusters reported with skin lesions and fever.",
  },
  {
    name: "Legionnaires’ Disease",
    status: "Isolated Outbreak",
    severity_level: "Medium",
    location: "Hotels",
    description: "Linked to contaminated cooling systems in buildings.",
  },
  {
    name: "Tonsillitis",
    status: "Stable",
    severity_level: "Low",
    location: "Community",
    description: "Routine cases of sore throat in children and adults.",
  },
  {
    name: "Strep Throat",
    status: "Increasing Slowly",
    severity_level: "Low",
    location: "Schools",
    description: "Cluster of bacterial throat infections reported.",
  },
  {
    name: "Pneumonia",
    status: "Increasing Rapidly",
    severity_level: "High",
    location: "Hospitals",
    description: "Severe respiratory cases requiring hospitalization.",
  },
  {
    name: "Bronchitis",
    status: "Stable",
    severity_level: "Medium",
    location: "Community",
    description: "Common respiratory illness observed seasonally.",
  },
  {
    name: "Otitis Media (Ear Infection)",
    status: "Stable",
    severity_level: "Low",
    location: "Nearby Clinics",
    description: "Mostly affecting children under five.",
  },
  {
    name: "Conjunctivitis (Pink Eye)",
    status: "Outbreak",
    severity_level: "Low",
    location: "Schools and Workplaces",
    description: "Highly contagious eye infection spreading rapidly.",
  },
];
